no longer ValueError when using the ``get_marker`` api.
