Fix ``TypeError`` when the assertion message is ``bytes`` in python 3.
