``logging.raiseExceptions`` is not set to ``False`` anymore.
